/**
 * GEC (Geopolitical Entities and Codes) to ISO Country Code Mapping
 * GEC codes are used by the CIA World Factbook
 * This maps GEC codes to standard country names for the factbook.json data
 * 
 * All entries are unique - no duplicate GEC codes
 */

export const gecToCountryMapping: Record<string, { gecCode: string; countryName: string; iso2: string }> = {
  // Africa
  "ag": { gecCode: "ag", countryName: "Algeria", iso2: "DZ" },
  "ao": { gecCode: "ao", countryName: "Angola", iso2: "AO" },
  "bf": { gecCode: "bf", countryName: "Burkina Faso", iso2: "BF" },
  "bn": { gecCode: "bn", countryName: "Benin", iso2: "BJ" },
  "cd": { gecCode: "cd", countryName: "Chad", iso2: "TD" },
  "cf": { gecCode: "cf", countryName: "Central African Republic", iso2: "CF" },
  "cg": { gecCode: "cg", countryName: "Congo", iso2: "CG" },
  "cm": { gecCode: "cm", countryName: "Cameroon", iso2: "CM" },
  "cn": { gecCode: "cn", countryName: "Comoros", iso2: "KM" },
  "ct": { gecCode: "ct", countryName: "Côte d'Ivoire", iso2: "CI" },
  "cv": { gecCode: "cv", countryName: "Cape Verde", iso2: "CV" },
  "dj": { gecCode: "dj", countryName: "Djibouti", iso2: "DJ" },
  "eg": { gecCode: "eg", countryName: "Egypt", iso2: "EG" },
  "ek": { gecCode: "ek", countryName: "Equatorial Guinea", iso2: "GQ" },
  "er": { gecCode: "er", countryName: "Eritrea", iso2: "ER" },
  "et": { gecCode: "et", countryName: "Ethiopia", iso2: "ET" },
  "ga": { gecCode: "ga", countryName: "Gabon", iso2: "GA" },
  "gb": { gecCode: "gb", countryName: "The Gambia", iso2: "GM" },
  "gh": { gecCode: "gh", countryName: "Ghana", iso2: "GH" },
  "gv": { gecCode: "gv", countryName: "Guinea", iso2: "GN" },
  "iv": { gecCode: "iv", countryName: "Guinea-Bissau", iso2: "GW" },
  "ke": { gecCode: "ke", countryName: "Kenya", iso2: "KE" },
  "li": { gecCode: "li", countryName: "Liberia", iso2: "LR" },
  "lt": { gecCode: "lt", countryName: "Lesotho", iso2: "LS" },
  "ly": { gecCode: "ly", countryName: "Libya", iso2: "LY" },
  "ma": { gecCode: "ma", countryName: "Morocco", iso2: "MA" },
  "mg": { gecCode: "mg", countryName: "Madagascar", iso2: "MG" },
  "mi": { gecCode: "mi", countryName: "Mauritius", iso2: "MU" },
  "ml": { gecCode: "ml", countryName: "Mali", iso2: "ML" },
  "mr": { gecCode: "mr", countryName: "Mauritania", iso2: "MR" },
  "mz": { gecCode: "mz", countryName: "Mozambique", iso2: "MZ" },
  "ng": { gecCode: "ng", countryName: "Nigeria", iso2: "NG" },
  "od": { gecCode: "od", countryName: "South Sudan", iso2: "SS" },
  "pu": { gecCode: "pu", countryName: "Seychelles", iso2: "SC" },
  "rw": { gecCode: "rw", countryName: "Rwanda", iso2: "RW" },
  "se": { gecCode: "se", countryName: "São Tomé and Príncipe", iso2: "ST" },
  "sf": { gecCode: "sf", countryName: "South Africa", iso2: "ZA" },
  "sh": { gecCode: "sh", countryName: "Sierra Leone", iso2: "SL" },
  "sn": { gecCode: "sn", countryName: "Senegal", iso2: "SN" },
  "so": { gecCode: "so", countryName: "Somalia", iso2: "SO" },
  "su": { gecCode: "su", countryName: "Sudan", iso2: "SD" },
  "ts": { gecCode: "ts", countryName: "Tunisia", iso2: "TN" },
  "tz": { gecCode: "tz", countryName: "Tanzania", iso2: "TZ" },
  "ug": { gecCode: "ug", countryName: "Uganda", iso2: "UG" },
  "wa": { gecCode: "wa", countryName: "Namibia", iso2: "NA" },
  "wi": { gecCode: "wi", countryName: "Western Sahara", iso2: "EH" },
  "wz": { gecCode: "wz", countryName: "Eswatini", iso2: "SZ" },
  "za": { gecCode: "za", countryName: "Zambia", iso2: "ZM" },
  "zi": { gecCode: "zi", countryName: "Zimbabwe", iso2: "ZW" },

  // Asia
  "af": { gecCode: "af", countryName: "Afghanistan", iso2: "AF" },
  "am": { gecCode: "am", countryName: "Armenia", iso2: "AM" },
  "az": { gecCode: "az", countryName: "Azerbaijan", iso2: "AZ" },
  "bh": { gecCode: "bh", countryName: "Bahrain", iso2: "BH" },
  "bg": { gecCode: "bg", countryName: "Bangladesh", iso2: "BD" },
  "bk": { gecCode: "bk", countryName: "Brunei", iso2: "BN" },
  "bt": { gecCode: "bt", countryName: "Bhutan", iso2: "BT" },
  "ch": { gecCode: "ch", countryName: "China", iso2: "CN" },
  "ci": { gecCode: "ci", countryName: "Sri Lanka", iso2: "LK" },
  "em": { gecCode: "em", countryName: "East Timor", iso2: "TL" },
  "gg": { gecCode: "gg", countryName: "Georgia", iso2: "GE" },
  "hk": { gecCode: "hk", countryName: "Hong Kong", iso2: "HK" },
  "in": { gecCode: "in", countryName: "India", iso2: "IN" },
  "io": { gecCode: "io", countryName: "British Indian Ocean Territory", iso2: "IO" },
  "id": { gecCode: "id", countryName: "Indonesia", iso2: "ID" },
  "ir": { gecCode: "ir", countryName: "Iran", iso2: "IR" },
  "iz": { gecCode: "iz", countryName: "Iraq", iso2: "IQ" },
  "is": { gecCode: "is", countryName: "Israel", iso2: "IL" },
  "ja": { gecCode: "ja", countryName: "Japan", iso2: "JP" },
  "jo": { gecCode: "jo", countryName: "Jordan", iso2: "JO" },
  "cb": { gecCode: "cb", countryName: "Cambodia", iso2: "KH" },
  "kg": { gecCode: "kg", countryName: "Kyrgyzstan", iso2: "KG" },
  "kn": { gecCode: "kn", countryName: "North Korea", iso2: "KP" },
  "ko": { gecCode: "ko", countryName: "South Korea", iso2: "KR" },
  "ku": { gecCode: "ku", countryName: "Kuwait", iso2: "KW" },
  "kz": { gecCode: "kz", countryName: "Kazakhstan", iso2: "KZ" },
  "la": { gecCode: "la", countryName: "Laos", iso2: "LA" },
  "le": { gecCode: "le", countryName: "Lebanon", iso2: "LB" },
  "mc": { gecCode: "mc", countryName: "Macau", iso2: "MO" },
  "mm": { gecCode: "mm", countryName: "Myanmar", iso2: "MM" },
  "mv": { gecCode: "mv", countryName: "Maldives", iso2: "MV" },
  "my": { gecCode: "my", countryName: "Malaysia", iso2: "MY" },
  "np": { gecCode: "np", countryName: "Nepal", iso2: "NP" },
  "mu": { gecCode: "mu", countryName: "Oman", iso2: "OM" },
  "pk": { gecCode: "pk", countryName: "Pakistan", iso2: "PK" },
  "rp": { gecCode: "rp", countryName: "Philippines", iso2: "PH" },
  "qa": { gecCode: "qa", countryName: "Qatar", iso2: "QA" },
  "rs": { gecCode: "rs", countryName: "Russia", iso2: "RU" },
  "sa": { gecCode: "sa", countryName: "Saudi Arabia", iso2: "SA" },
  "sg": { gecCode: "sg", countryName: "Singapore", iso2: "SG" },
  "sy": { gecCode: "sy", countryName: "Syria", iso2: "SY" },
  "tw": { gecCode: "tw", countryName: "Taiwan", iso2: "TW" },
  "th": { gecCode: "th", countryName: "Thailand", iso2: "TH" },
  "ti": { gecCode: "ti", countryName: "Tajikistan", iso2: "TJ" },
  "tk": { gecCode: "tk", countryName: "Turkmenistan", iso2: "TM" },
  "tl": { gecCode: "tl", countryName: "East Timor", iso2: "TL" },
  "tn": { gecCode: "tn", countryName: "Turkey", iso2: "TR" },
  "up": { gecCode: "up", countryName: "Ukraine", iso2: "UA" },
  "ae": { gecCode: "ae", countryName: "United Arab Emirates", iso2: "AE" },
  "uz": { gecCode: "uz", countryName: "Uzbekistan", iso2: "UZ" },
  "vm": { gecCode: "vm", countryName: "Vietnam", iso2: "VN" },
  "ym": { gecCode: "ym", countryName: "Yemen", iso2: "YE" },

  // Europe
  "al": { gecCode: "al", countryName: "Albania", iso2: "AL" },
  "an": { gecCode: "an", countryName: "Andorra", iso2: "AD" },
  "au": { gecCode: "au", countryName: "Austria", iso2: "AT" },
  "ba": { gecCode: "ba", countryName: "Bosnia and Herzegovina", iso2: "BA" },
  "be": { gecCode: "be", countryName: "Belgium", iso2: "BE" },
  "by": { gecCode: "by", countryName: "Belarus", iso2: "BY" },
  "bu": { gecCode: "bu", countryName: "Bulgaria", iso2: "BG" },
  "cy": { gecCode: "cy", countryName: "Cyprus", iso2: "CY" },
  "cz": { gecCode: "cz", countryName: "Czech Republic", iso2: "CZ" },
  "da": { gecCode: "da", countryName: "Denmark", iso2: "DK" },
  "ei": { gecCode: "ei", countryName: "Ireland", iso2: "IE" },
  "en": { gecCode: "en", countryName: "Estonia", iso2: "EE" },
  "fi": { gecCode: "fi", countryName: "Finland", iso2: "FI" },
  "fr": { gecCode: "fr", countryName: "France", iso2: "FR" },
  "gm": { gecCode: "gm", countryName: "Germany", iso2: "DE" },
  "gi": { gecCode: "gi", countryName: "Gibraltar", iso2: "GI" },
  "gr": { gecCode: "gr", countryName: "Greece", iso2: "GR" },
  "gk": { gecCode: "gk", countryName: "Guernsey", iso2: "GG" },
  "hu": { gecCode: "hu", countryName: "Hungary", iso2: "HU" },
  "hr": { gecCode: "hr", countryName: "Croatia", iso2: "HR" },
  "ic": { gecCode: "ic", countryName: "Iceland", iso2: "IS" },
  "im": { gecCode: "im", countryName: "Isle of Man", iso2: "IM" },
  "it": { gecCode: "it", countryName: "Italy", iso2: "IT" },
  "je": { gecCode: "je", countryName: "Jersey", iso2: "JE" },
  "ks": { gecCode: "ks", countryName: "Kosovo", iso2: "XK" },
  "lh": { gecCode: "lh", countryName: "Liechtenstein", iso2: "LI" },
  "lu": { gecCode: "lu", countryName: "Luxembourg", iso2: "LU" },
  "lv": { gecCode: "lv", countryName: "Latvia", iso2: "LV" },
  "mo": { gecCode: "mo", countryName: "Monaco", iso2: "MC" },
  "nm": { gecCode: "nm", countryName: "North Macedonia", iso2: "MK" },
  "mt": { gecCode: "mt", countryName: "Malta", iso2: "MT" },
  "md": { gecCode: "md", countryName: "Moldova", iso2: "MD" },
  "mn": { gecCode: "mn", countryName: "Montenegro", iso2: "ME" },
  "nl": { gecCode: "nl", countryName: "Netherlands", iso2: "NL" },
  "no": { gecCode: "no", countryName: "Norway", iso2: "NO" },
  "pl": { gecCode: "pl", countryName: "Poland", iso2: "PL" },
  "po": { gecCode: "po", countryName: "Portugal", iso2: "PT" },
  "ps": { gecCode: "ps", countryName: "Palestine", iso2: "PS" },
  "ro": { gecCode: "ro", countryName: "Romania", iso2: "RO" },
  "ri": { gecCode: "ri", countryName: "Serbia", iso2: "RS" },
  "si": { gecCode: "si", countryName: "Slovenia", iso2: "SI" },
  "sk": { gecCode: "sk", countryName: "Slovakia", iso2: "SK" },
  "sm": { gecCode: "sm", countryName: "San Marino", iso2: "SM" },
  "sp": { gecCode: "sp", countryName: "Spain", iso2: "ES" },
  "sv": { gecCode: "sv", countryName: "Sweden", iso2: "SE" },
  "sw": { gecCode: "sw", countryName: "Switzerland", iso2: "CH" },
  "uk": { gecCode: "uk", countryName: "United Kingdom", iso2: "GB" },
  "vt": { gecCode: "vt", countryName: "Vatican City", iso2: "VA" },

  // Americas
  "ac": { gecCode: "ac", countryName: "Antigua and Barbuda", iso2: "AG" },
  "ar": { gecCode: "ar", countryName: "Argentina", iso2: "AR" },
  "bb": { gecCode: "bb", countryName: "Barbados", iso2: "BB" },
  "bd": { gecCode: "bd", countryName: "Bermuda", iso2: "BM" },
  "bs": { gecCode: "bs", countryName: "Bahamas", iso2: "BS" },
  "bo": { gecCode: "bo", countryName: "Bolivia", iso2: "BO" },
  "br": { gecCode: "br", countryName: "Brazil", iso2: "BR" },
  "ca": { gecCode: "ca", countryName: "Canada", iso2: "CA" },
  "cj": { gecCode: "cj", countryName: "Chile", iso2: "CL" },
  "cu": { gecCode: "cu", countryName: "Cuba", iso2: "CU" },
  "co": { gecCode: "co", countryName: "Colombia", iso2: "CO" },
  "cq": { gecCode: "cq", countryName: "Costa Rica", iso2: "CR" },
  "dd": { gecCode: "dd", countryName: "Dominica", iso2: "DM" },
  "do": { gecCode: "do", countryName: "Dominican Republic", iso2: "DO" },
  "ec": { gecCode: "ec", countryName: "Ecuador", iso2: "EC" },
  "el": { gecCode: "el", countryName: "El Salvador", iso2: "SV" },
  "gj": { gecCode: "gj", countryName: "Grenada", iso2: "GD" },
  "gl": { gecCode: "gl", countryName: "Greenland", iso2: "GL" },
  "gt": { gecCode: "gt", countryName: "Guatemala", iso2: "GT" },
  "gy": { gecCode: "gy", countryName: "Guyana", iso2: "GY" },
  "ha": { gecCode: "ha", countryName: "Haiti", iso2: "HT" },
  "ho": { gecCode: "ho", countryName: "Honduras", iso2: "HN" },
  "jm": { gecCode: "jm", countryName: "Jamaica", iso2: "JM" },
  "me": { gecCode: "me", countryName: "Mexico", iso2: "MX" },
  "ni": { gecCode: "ni", countryName: "Nicaragua", iso2: "NI" },
  "pa": { gecCode: "pa", countryName: "Panama", iso2: "PA" },
  "pe": { gecCode: "pe", countryName: "Peru", iso2: "PE" },
  "pq": { gecCode: "pq", countryName: "Puerto Rico", iso2: "PR" },
  "sc": { gecCode: "sc", countryName: "Saint Kitts and Nevis", iso2: "KN" },
  "sj": { gecCode: "sj", countryName: "Saint Lucia", iso2: "LC" },
  "st": { gecCode: "st", countryName: "Saint Vincent and the Grenadines", iso2: "VC" },
  "sr": { gecCode: "sr", countryName: "Suriname", iso2: "SR" },
  "td": { gecCode: "td", countryName: "Trinidad and Tobago", iso2: "TT" },
  "uy": { gecCode: "uy", countryName: "Uruguay", iso2: "UY" },
  "us": { gecCode: "us", countryName: "United States", iso2: "US" },
  "ve": { gecCode: "ve", countryName: "Venezuela", iso2: "VE" },

  // Oceania
  "as": { gecCode: "as", countryName: "Australia", iso2: "AU" },
  "fj": { gecCode: "fj", countryName: "Fiji", iso2: "FJ" },
  "fm": { gecCode: "fm", countryName: "Micronesia", iso2: "FM" },
  "ki": { gecCode: "ki", countryName: "Kiribati", iso2: "KI" },
  "mh": { gecCode: "mh", countryName: "Marshall Islands", iso2: "MH" },
  "nz": { gecCode: "nz", countryName: "New Zealand", iso2: "NZ" },
  "nr": { gecCode: "nr", countryName: "Nauru", iso2: "NR" },
  "pw": { gecCode: "pw", countryName: "Palau", iso2: "PW" },
  "pp": { gecCode: "pp", countryName: "Papua New Guinea", iso2: "PG" },
  "sb": { gecCode: "sb", countryName: "Solomon Islands", iso2: "SB" },
  "to": { gecCode: "to", countryName: "Tonga", iso2: "TO" },
  "tv": { gecCode: "tv", countryName: "Tuvalu", iso2: "TV" },
  "ws": { gecCode: "ws", countryName: "Samoa", iso2: "WS" },
};

/**
 * Aliases for country name variations used in COUNTRIES list
 */
const countryNameAliases: Record<string, string> = {
  // Country name variations to gecCode
  "the gambia": "gb",
  "gambia": "gb",
  "congo": "cg",
  "republic of the congo": "cg",
  "congo-brazzaville": "cg",
  "democratic republic of the congo": "cd",
  "democratic republic of congo": "cd",
  "dr congo": "cd",
  "congo-kinshasa": "cd",
  "ivory coast": "ct",
  "côte d'ivoire": "ct",
  "cote d'ivoire": "ct",
  "guinea-bissau": "iv",
  "guinea bissau": "iv",
  "northern cyprus": "cy",
  "republic of serbia": "ri",
  "united states of america": "us",
  "united states": "us",
  "united kingdom": "uk",
  "east timor": "tl",
  "timor-leste": "tl",
  "eswatini": "wz",
  "swaziland": "wz",
  "the bahamas": "bs",
  "bahamas": "bs",
  "san marino": "sm",
  "saint kitts and nevis": "sc",
  "saint lucia": "sj",
  "saint vincent and the grenadines": "st",
  "sao tome and principe": "se",
  "são tomé and príncipe": "se",
  "vatican city": "vt",
  "holy see": "vt",
  "micronesia": "fm",
  "federated states of micronesia": "fm",
  "marshall islands": "mr",
  "republic of the marshall islands": "mr",
  "nauru": "nr",
  "republic of nauru": "nr",
  // Additional countries from COUNTRIES list
  "barbados": "bb",
  "cape verde": "cv",
  "comoros": "cn",
  "dominica": "dd",
  "falkland islands": "fk",
  "french guiana": "fg",
  "french southern and antarctic lands": "fs",
  "greenland": "gl",
  "liechtenstein": "lh",
  "maldives": "mv",
  "malta": "mt",
  "monaco": "mo",
  "new caledonia": "nc",
  "palau": "pw",
  "papua new guinea": "pp",
  "puerto rico": "pr",
  "samoa": "ws",
  "seychelles": "pu",
  "sierra leone": "sh",
  "singapore": "sg",
  "solomon islands": "sb",
  "somalia": "so",
  "somaliland": "so",
  "south sudan": "od",
  "tonga": "to",
  "trinidad and tobago": "td",
  "tuvalu": "tv",
  "west bank": "we",
  "western sahara": "wi",
  "australia": "as",
  "algeria": "ag",
  "belarus": "by",
  "benin": "bn",
  "macao": "mc",
  "macau": "mc",
  "mauritania": "mr",
  // Americas
  "antigua and barbuda": "ac",
  "argentina": "ar",
  "bolivia": "bo",
  "chile": "cj",
  "costa rica": "cq",
  "dominican republic": "do",
  "el salvador": "el",
  "grenada": "gj",
  "guyana": "gy",
  "honduras": "ho",
  "jamaica": "jm",
  "nicaragua": "ni",
  "panama": "pa",
  "suriname": "sr",
  "uruguay": "uy",
  "venezuela": "ve",
  // Europe
  "bosnia and herzegovina": "ba",
  "croatia": "hr",
  "kosovo": "ks",
  "palestine": "ps",
  // Africa
  "bermuda": "bd",
  "cameroon": "cm",
  "central african republic": "cf",
  "djibouti": "dj",
  "equatorial guinea": "ek",
  "ethiopia": "et",
  "gabon": "ga",
  "ghana": "gh",
  "guinea": "gv",
  "kenya": "ke",
  "lesotho": "lt",
  "mozambique": "mz",
  "namibia": "wa",
  "rwanda": "rw",
  "senegal": "sn",
  "sudan": "su",
  "tanzania": "tz",
  "uganda": "ug",
  "zambia": "za",
  "zimbabwe": "zi",
  // Europe/Asia
  "andorra": "an",
  "austria": "au",
  "belgium": "be",
  "bulgaria": "bu",
  "czech republic": "cz",
  "denmark": "da",
  "estonia": "en",
  "finland": "fi",
  "france": "fr",
  "germany": "gm",
  "gibraltar": "gi",
  "greece": "gr",
  "hungary": "hu",
  "iceland": "ic",
  "ireland": "ei",
  "italy": "it",
  "latvia": "lv",
  "luxembourg": "lu",
  "north macedonia": "nm",
  "moldova": "md",
  "montenegro": "mn",
  "netherlands": "nl",
  "norway": "no",
  "poland": "pl",
  "portugal": "po",
  "romania": "ro",
  "russia": "rs",
  "slovakia": "sk",
  "slovenia": "si",
  "spain": "sp",
  "sweden": "sv",
  "switzerland": "sw",
};

/**
 * Get GEC code from country name
 */
export function getGecCode(countryName: string): string | undefined {
  const normalized = countryName.toLowerCase().trim();
  
  // Check aliases first
  if (countryNameAliases[normalized]) {
    return countryNameAliases[normalized];
  }
  
  // Direct lookup
  for (const [gecCode, data] of Object.entries(gecToCountryMapping)) {
    if (data.countryName.toLowerCase() === normalized) {
      return gecCode;
    }
  }

  // Partial match
  for (const [gecCode, data] of Object.entries(gecToCountryMapping)) {
    if (data.countryName.toLowerCase().includes(normalized) || 
        normalized.includes(data.countryName.toLowerCase())) {
      return gecCode;
    }
  }

  return undefined;
}

/**
 * Get country info from GEC code
 */
export function getCountryFromGec(gecCode: string): { countryName: string; iso2: string } | undefined {
  return gecToCountryMapping[gecCode.toLowerCase()];
}
